apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tf-lambda
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: ssh-credentials
  url: ssh://git@github.com/aacecandev/tf-lambda